/**
 * Versioned retirement-opportunity-v1 assessment definition.
 * Questions are configuration — not UI hard-codes.
 */

export type AssessmentStageKey =
  | "ABOUT_YOU"
  | "YOUR_MONEY"
  | "YOUR_GOAL"
  | "DYNAMIC_BRANCH"
  | "YOUR_PRIORITIES"
  | "YOUR_PLAN"
  | "CONTACT";

export const ASSESSMENT_STAGE_LABELS: Record<AssessmentStageKey, string> = {
  ABOUT_YOU: "ABOUT YOU",
  YOUR_MONEY: "YOUR MONEY",
  YOUR_GOAL: "YOUR GOALS",
  DYNAMIC_BRANCH: "YOUR GOALS",
  YOUR_PRIORITIES: "YOUR PRIORITIES",
  YOUR_PLAN: "YOUR PLAN",
  CONTACT: "CONTACT",
};

/** US states for Q2 — configuration, not UI hard-codes. */
export const US_STATES = [
  "AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA",
  "KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ",
  "NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT",
  "VA","WA","WV","WI","WY","DC",
] as const;

export type AssessmentQuestionDef = {
  id: string;
  number: number;
  stage: AssessmentStageKey;
  label: string;
  type: "single" | "multi" | "slider" | "cards";
  options?: string[];
  /** Consumer-facing labels keyed by stored option value */
  option_labels?: Record<string, string>;
  required: boolean;
  branch?: "core" | "accumulation" | "income" | "both" | "conditional";
  condition?: { when_key: string; when_values: string[] };
  scoring_dimension?: string;
  analytics_key: string;
};

export const RETIREMENT_OPPORTUNITY_V1 = {
  key: "retirement-opportunity-v1",
  version: "v1",
  title: "Retirement Opportunity Profile",
  questions: [
    {
      id: "age_range",
      number: 1,
      stage: "ABOUT_YOU",
      label: "How old are you?",
      type: "cards",
      options: ["Under 45", "45–49", "50–54", "55–59", "60–64", "65–69", "70–74", "75+"],
      required: true,
      branch: "core",
      analytics_key: "age_range",
    },
    {
      id: "state",
      number: 2,
      stage: "ABOUT_YOU",
      label: "Where do you currently live?",
      type: "cards",
      options: [...US_STATES],
      required: true,
      branch: "core",
      analytics_key: "state",
    },
    {
      id: "employment",
      number: 3,
      stage: "ABOUT_YOU",
      label: "Which best describes your current employment situation?",
      type: "cards",
      options: ["Working", "Self-employed", "Retired", "Semi-retired"],
      required: true,
      branch: "core",
      analytics_key: "employment",
    },
    {
      id: "retirement_timing",
      number: 4,
      stage: "ABOUT_YOU",
      label: "When do you expect to retire?",
      type: "cards",
      options: [
        "Already retired",
        "Within 2 years",
        "2–5 years",
        "5–10 years",
        "10+ years",
      ],
      required: true,
      branch: "core",
      scoring_dimension: "retirement_need",
      analytics_key: "retirement_timing",
    },
    {
      id: "marital_status",
      number: 5,
      stage: "ABOUT_YOU",
      label: "What is your marital status?",
      type: "cards",
      options: ["Single", "Married", "Widowed", "Divorced"],
      required: false,
      branch: "core",
      analytics_key: "marital_status",
    },
    {
      id: "total_retirement_assets",
      number: 6,
      stage: "YOUR_MONEY",
      label: "Approximately how much do you currently have in investable or retirement assets?",
      type: "cards",
      options: [
        "Under $250K",
        "$250K–$499K",
        "$500K–$749K",
        "$750K–$999K",
        "$1M–$1.99M",
        "$2M+",
        "$3M+",
      ],
      required: true,
      branch: "core",
      scoring_dimension: "opportunity_size",
      analytics_key: "total_retirement_assets",
    },
    {
      id: "repositionable_assets",
      number: 7,
      stage: "YOUR_MONEY",
      label: "Approximately how much could potentially be repositioned into a different retirement strategy if you found a better fit?",
      type: "cards",
      options: [
        "Under $250K",
        "$250K–$499K",
        "$500K–$749K",
        "$750K–$999K",
        "$1M+",
        "$3M+",
      ],
      required: true,
      branch: "core",
      scoring_dimension: "opportunity_size",
      analytics_key: "repositionable_assets",
    },
    {
      id: "asset_location",
      number: 8,
      stage: "YOUR_MONEY",
      label: "Where is most of this money currently held?",
      type: "multi",
      options: [
        "401(k)",
        "403(b)",
        "457",
        "IRA",
        "Brokerage",
        "CDs",
        "Savings",
        "Existing Annuity",
        "Other",
      ],
      required: true,
      branch: "core",
      scoring_dimension: "strategy_alignment",
      analytics_key: "asset_location",
    },
    {
      id: "employer_assets",
      number: 9,
      stage: "YOUR_MONEY",
      label: "Are any retirement assets held with a current or former employer?",
      type: "cards",
      options: ["Current employer", "Former employer", "No employer-sponsored assets"],
      required: true,
      branch: "core",
      scoring_dimension: "strategy_alignment",
      analytics_key: "employer_assets",
    },
    {
      id: "existing_annuity",
      number: 10,
      stage: "YOUR_MONEY",
      label: "Do you currently own an annuity?",
      type: "cards",
      options: [
        "None",
        "Fixed Indexed Annuity",
        "Variable Annuity",
        "Fixed / MYGA",
        "I have one but don't know the type",
      ],
      required: true,
      branch: "core",
      scoring_dimension: "strategy_alignment",
      analytics_key: "existing_annuity",
    },
    {
      id: "liquidity_timeline",
      number: 11,
      stage: "YOUR_MONEY",
      label: "How soon might you need access to a meaningful portion of this money?",
      type: "cards",
      options: ["Within 1 year", "1–3 years", "3–5 years", "5–10 years", "10+ years"],
      required: true,
      branch: "core",
      scoring_dimension: "strategy_alignment",
      analytics_key: "liquidity_timeline",
    },
    {
      id: "primary_objective",
      number: 12,
      stage: "YOUR_GOAL",
      label: "What's most important with this money?",
      type: "cards",
      options: ["GROW", "INCOME", "PROTECT", "BALANCE", "LEGACY"],
      option_labels: {
        GROW: "Growth",
        INCOME: "Income",
        PROTECT: "Protection",
        BALANCE: "Income + Protection",
        LEGACY: "Legacy",
      },
      required: true,
      branch: "core",
      scoring_dimension: "strategy_alignment",
      analytics_key: "primary_objective",
    },
    // Accumulation branch
    {
      id: "principal_protection",
      number: 13,
      stage: "DYNAMIC_BRANCH",
      label: "How important is protecting your principal from market losses?",
      type: "slider",
      required: true,
      branch: "accumulation",
      condition: {
        when_key: "primary_objective",
        when_values: ["GROW", "PROTECT", "BALANCE"],
      },
      scoring_dimension: "retirement_need",
      analytics_key: "principal_protection",
    },
    {
      id: "growth_participation",
      number: 14,
      stage: "DYNAMIC_BRANCH",
      label: "How important is continuing to participate in market growth potential?",
      type: "slider",
      required: true,
      branch: "accumulation",
      condition: {
        when_key: "primary_objective",
        when_values: ["GROW", "PROTECT", "BALANCE"],
      },
      scoring_dimension: "retirement_need",
      analytics_key: "growth_participation",
    },
    {
      id: "market_drop_concern",
      number: 15,
      stage: "DYNAMIC_BRANCH",
      label: "If the market dropped 20–30%, how concerned would you be about your retirement savings?",
      type: "cards",
      options: [
        "Not concerned",
        "Somewhat concerned",
        "Very concerned",
        "Extremely concerned",
      ],
      required: true,
      branch: "accumulation",
      condition: {
        when_key: "primary_objective",
        when_values: ["GROW", "PROTECT"],
      },
      scoring_dimension: "retirement_need",
      analytics_key: "market_drop_concern",
    },
    {
      id: "risk_growth_preference",
      number: 16,
      stage: "DYNAMIC_BRANCH",
      label: "Which sounds most like you?",
      type: "cards",
      options: ["A", "B", "C"],
      option_labels: {
        A: "I'm comfortable accepting market losses for potentially higher returns.",
        B: "I'd prefer some growth potential without directly losing money due to market declines.",
        C: "Protecting my principal is more important than maximizing growth.",
      },
      required: true,
      branch: "accumulation",
      condition: {
        when_key: "primary_objective",
        when_values: ["GROW", "PROTECT"],
      },
      scoring_dimension: "strategy_alignment",
      analytics_key: "risk_growth_preference",
    },
    // Income branch
    {
      id: "income_start",
      number: 13,
      stage: "DYNAMIC_BRANCH",
      label: "When would you like retirement income to begin?",
      type: "cards",
      options: ["Immediately", "Within 1 year", "1–3 years", "3–5 years", "5+ years"],
      required: true,
      branch: "income",
      condition: {
        when_key: "primary_objective",
        when_values: ["INCOME", "BALANCE"],
      },
      scoring_dimension: "retirement_need",
      analytics_key: "income_start",
    },
    {
      id: "desired_monthly_income",
      number: 14,
      stage: "DYNAMIC_BRANCH",
      label: "Approximately how much monthly retirement income would you like your strategy to help provide?",
      type: "cards",
      options: [
        "Under $2,500",
        "$2,500–$5,000",
        "$5,000–$7,500",
        "$7,500–$10,000",
        "$10,000+",
      ],
      required: true,
      branch: "income",
      condition: {
        when_key: "primary_objective",
        when_values: ["INCOME"],
      },
      scoring_dimension: "retirement_need",
      analytics_key: "desired_monthly_income",
    },
    {
      id: "lifetime_income_importance",
      number: 15,
      stage: "DYNAMIC_BRANCH",
      label: "How important is having retirement income designed to last throughout your lifetime?",
      type: "slider",
      required: true,
      branch: "income",
      condition: {
        when_key: "primary_objective",
        when_values: ["INCOME", "BALANCE"],
      },
      scoring_dimension: "retirement_need",
      analytics_key: "lifetime_income_importance",
    },
    {
      id: "existing_guaranteed_income",
      number: 16,
      stage: "DYNAMIC_BRANCH",
      label: "Do you currently have guaranteed lifetime income besides Social Security?",
      type: "cards",
      options: ["Pension", "Existing annuity", "Both", "Neither"],
      required: true,
      branch: "income",
      condition: {
        when_key: "primary_objective",
        when_values: ["INCOME"],
      },
      scoring_dimension: "retirement_need",
      analytics_key: "existing_guaranteed_income",
    },
    // Universal rejoined
    {
      id: "inflation_concern",
      number: 17,
      stage: "YOUR_PRIORITIES",
      label: "How concerned are you about inflation reducing your purchasing power during retirement?",
      type: "slider",
      required: true,
      branch: "core",
      scoring_dimension: "retirement_need",
      analytics_key: "inflation_concern",
    },
    {
      id: "liquidity_importance",
      number: 18,
      stage: "YOUR_PRIORITIES",
      label: "How important is maintaining access to some of your money for emergencies or unexpected expenses?",
      type: "slider",
      required: true,
      branch: "core",
      scoring_dimension: "strategy_alignment",
      analytics_key: "liquidity_importance",
    },
    {
      id: "legacy_importance",
      number: 19,
      stage: "YOUR_PRIORITIES",
      label: "How important is leaving money to your spouse, children or beneficiaries?",
      type: "slider",
      required: false,
      branch: "core",
      analytics_key: "legacy_importance",
    },
    {
      id: "healthcare_concern",
      number: 20,
      stage: "YOUR_PRIORITIES",
      label: "How concerned are you about healthcare or long-term-care expenses affecting your retirement savings?",
      type: "slider",
      required: false,
      branch: "core",
      scoring_dimension: "retirement_need",
      analytics_key: "healthcare_concern",
    },
    {
      id: "carrier_strength_importance",
      number: 21,
      stage: "YOUR_PRIORITIES",
      label: "How important is the financial strength and rating of the insurance company protecting retirement assets?",
      type: "slider",
      required: false,
      branch: "core",
      analytics_key: "carrier_strength_importance",
    },
    {
      id: "advisor_team_importance",
      number: 22,
      stage: "YOUR_PRIORITIES",
      label: "How important is working with an experienced retirement planning team rather than making these decisions alone?",
      type: "slider",
      required: false,
      branch: "core",
      analytics_key: "advisor_team_importance",
    },
    {
      id: "current_advisor",
      number: 23,
      stage: "YOUR_PLAN",
      label: "Are you currently working with a financial professional?",
      type: "cards",
      options: [
        "Yes, actively",
        "Yes, but I'm considering alternatives",
        "Not currently",
      ],
      required: true,
      branch: "core",
      scoring_dimension: "intent_timing",
      analytics_key: "current_advisor",
    },
    {
      id: "advisor_improvement",
      number: 23,
      stage: "YOUR_PLAN",
      label: "What would you most like improved about your current retirement strategy?",
      type: "cards",
      options: [
        "Growth",
        "Safety",
        "Income",
        "Fees",
        "Communication",
        "Tax efficiency",
        "Diversification",
        "Not sure",
      ],
      required: false,
      branch: "conditional",
      condition: {
        when_key: "current_advisor",
        when_values: [
          "Yes, actively",
          "Yes, but I'm considering alternatives",
        ],
      },
      analytics_key: "advisor_improvement",
    },
    {
      id: "decision_timeline",
      number: 24,
      stage: "YOUR_PLAN",
      label: "If you found a strategy that better matched your retirement goals, when would you be comfortable making a change?",
      type: "cards",
      options: [
        "Immediately",
        "Within 30 days",
        "1–3 months",
        "3–6 months",
        "6–12 months",
        "Just researching",
      ],
      required: true,
      branch: "core",
      scoring_dimension: "intent_timing",
      analytics_key: "decision_timeline",
    },
  ] satisfies AssessmentQuestionDef[],
};

export function getApplicableQuestions(answers: Record<string, string>) {
  return RETIREMENT_OPPORTUNITY_V1.questions.filter((q) => {
    if (!q.condition) return true;
    const value = answers[q.condition.when_key];
    return Boolean(value && q.condition.when_values.includes(value));
  });
}
