/**
 * Versioned retirement-opportunity-v1 assessment definition.
 * Questions are configuration — not UI hard-codes.
 */

export type AssessmentQuestionDef = {
  id: string;
  number: number;
  stage:
    | "ABOUT_YOU"
    | "YOUR_RETIREMENT"
    | "YOUR_MONEY"
    | "YOUR_PRIORITIES"
    | "YOUR_PLAN"
    | "ALMOST_DONE";
  label: string;
  type: "single" | "multi" | "slider" | "cards";
  options?: string[];
  required: boolean;
  branch?: "core" | "accumulation" | "income" | "both" | "conditional";
  condition?: { when_key: string; when_values: string[] };
  scoring_dimension?: string;
  analytics_key: string;
};

export const RETIREMENT_OPPORTUNITY_V1 = {
  key: "retirement-opportunity-v1",
  version: "v1",
  title: "Retirement Opportunity Profile",
  questions: [
    {
      id: "age_range",
      number: 1,
      stage: "ABOUT_YOU",
      label: "Age range",
      type: "cards",
      options: ["Under 45", "45–49", "50–54", "55–59", "60–64", "65–69", "70–74", "75+"],
      required: true,
      branch: "core",
      analytics_key: "age_range",
    },
    {
      id: "state",
      number: 2,
      stage: "ABOUT_YOU",
      label: "State of residence",
      type: "single",
      required: true,
      branch: "core",
      analytics_key: "state",
    },
    {
      id: "employment",
      number: 3,
      stage: "ABOUT_YOU",
      label: "Employment situation",
      type: "cards",
      options: ["Working", "Self-employed", "Retired", "Semi-retired"],
      required: true,
      branch: "core",
      analytics_key: "employment",
    },
    {
      id: "retirement_timing",
      number: 4,
      stage: "YOUR_RETIREMENT",
      label: "Expected retirement timing",
      type: "cards",
      options: [
        "Already retired",
        "Within 2 years",
        "2–5 years",
        "5–10 years",
        "10+ years",
      ],
      required: true,
      branch: "core",
      scoring_dimension: "retirement_need",
      analytics_key: "retirement_timing",
    },
    {
      id: "marital_status",
      number: 5,
      stage: "ABOUT_YOU",
      label: "Marital status",
      type: "cards",
      options: ["Single", "Married", "Widowed", "Divorced"],
      required: false,
      branch: "core",
      analytics_key: "marital_status",
    },
    {
      id: "total_retirement_assets",
      number: 6,
      stage: "YOUR_MONEY",
      label: "Investable / retirement assets",
      type: "cards",
      options: [
        "Under $250K",
        "$250K–$499K",
        "$500K–$749K",
        "$750K–$999K",
        "$1M–$1.99M",
        "$2M+",
        "$3M+",
      ],
      required: true,
      branch: "core",
      scoring_dimension: "opportunity_size",
      analytics_key: "total_retirement_assets",
    },
    {
      id: "repositionable_assets",
      number: 7,
      stage: "YOUR_MONEY",
      label: "Potentially repositionable assets",
      type: "cards",
      options: [
        "Under $250K",
        "$250K–$499K",
        "$500K–$749K",
        "$750K–$999K",
        "$1M+",
        "$3M+",
      ],
      required: true,
      branch: "core",
      scoring_dimension: "opportunity_size",
      analytics_key: "repositionable_assets",
    },
    {
      id: "asset_location",
      number: 8,
      stage: "YOUR_MONEY",
      label: "Where money is held",
      type: "multi",
      options: [
        "401(k)",
        "403(b)",
        "457",
        "IRA",
        "Brokerage",
        "CDs",
        "Savings",
        "Existing Annuity",
        "Other",
      ],
      required: true,
      branch: "core",
      scoring_dimension: "strategy_alignment",
      analytics_key: "asset_location",
    },
    {
      id: "employer_assets",
      number: 9,
      stage: "YOUR_MONEY",
      label: "Employer-sponsored assets",
      type: "cards",
      options: ["Current employer", "Former employer", "No employer-sponsored assets"],
      required: true,
      branch: "core",
      scoring_dimension: "strategy_alignment",
      analytics_key: "employer_assets",
    },
    {
      id: "existing_annuity",
      number: 10,
      stage: "YOUR_MONEY",
      label: "Existing annuity",
      type: "cards",
      options: [
        "None",
        "Fixed Indexed Annuity",
        "Variable Annuity",
        "Fixed / MYGA",
        "I have one but don't know the type",
      ],
      required: true,
      branch: "core",
      scoring_dimension: "strategy_alignment",
      analytics_key: "existing_annuity",
    },
    {
      id: "liquidity_timeline",
      number: 11,
      stage: "YOUR_MONEY",
      label: "Liquidity timeline",
      type: "cards",
      options: ["Within 1 year", "1–3 years", "3–5 years", "5–10 years", "10+ years"],
      required: true,
      branch: "core",
      scoring_dimension: "strategy_alignment",
      analytics_key: "liquidity_timeline",
    },
    {
      id: "primary_objective",
      number: 12,
      stage: "YOUR_PRIORITIES",
      label: "What's most important with this money?",
      type: "cards",
      options: ["GROW", "INCOME", "PROTECT", "BALANCE", "LEGACY"],
      required: true,
      branch: "core",
      scoring_dimension: "strategy_alignment",
      analytics_key: "primary_objective",
    },
    // Accumulation branch
    {
      id: "principal_protection",
      number: 13,
      stage: "YOUR_PRIORITIES",
      label: "Principal protection importance",
      type: "slider",
      required: true,
      branch: "accumulation",
      condition: {
        when_key: "primary_objective",
        when_values: ["GROW", "PROTECT", "BALANCE"],
      },
      scoring_dimension: "retirement_need",
      analytics_key: "principal_protection",
    },
    {
      id: "growth_participation",
      number: 14,
      stage: "YOUR_PRIORITIES",
      label: "Growth participation importance",
      type: "slider",
      required: true,
      branch: "accumulation",
      condition: {
        when_key: "primary_objective",
        when_values: ["GROW", "PROTECT", "BALANCE"],
      },
      scoring_dimension: "retirement_need",
      analytics_key: "growth_participation",
    },
    {
      id: "market_drop_concern",
      number: 15,
      stage: "YOUR_PRIORITIES",
      label: "Market drop concern",
      type: "cards",
      options: [
        "Not concerned",
        "Somewhat concerned",
        "Very concerned",
        "Extremely concerned",
      ],
      required: true,
      branch: "accumulation",
      condition: {
        when_key: "primary_objective",
        when_values: ["GROW", "PROTECT", "BALANCE"],
      },
      scoring_dimension: "retirement_need",
      analytics_key: "market_drop_concern",
    },
    {
      id: "risk_growth_preference",
      number: 16,
      stage: "YOUR_PRIORITIES",
      label: "Risk / growth preference",
      type: "cards",
      options: ["A", "B", "C"],
      required: true,
      branch: "accumulation",
      condition: {
        when_key: "primary_objective",
        when_values: ["GROW", "PROTECT"],
      },
      scoring_dimension: "strategy_alignment",
      analytics_key: "risk_growth_preference",
    },
    // Income branch
    {
      id: "income_start",
      number: 13,
      stage: "YOUR_PRIORITIES",
      label: "Income start timing",
      type: "cards",
      options: ["Immediately", "Within 1 year", "1–3 years", "3–5 years", "5+ years"],
      required: true,
      branch: "income",
      condition: {
        when_key: "primary_objective",
        when_values: ["INCOME", "BALANCE"],
      },
      scoring_dimension: "retirement_need",
      analytics_key: "income_start",
    },
    {
      id: "desired_monthly_income",
      number: 14,
      stage: "YOUR_PRIORITIES",
      label: "Desired monthly income",
      type: "cards",
      options: [
        "Under $2,500",
        "$2,500–$5,000",
        "$5,000–$7,500",
        "$7,500–$10,000",
        "$10,000+",
      ],
      required: true,
      branch: "income",
      condition: {
        when_key: "primary_objective",
        when_values: ["INCOME", "BALANCE"],
      },
      scoring_dimension: "retirement_need",
      analytics_key: "desired_monthly_income",
    },
    {
      id: "lifetime_income_importance",
      number: 15,
      stage: "YOUR_PRIORITIES",
      label: "Lifetime income importance",
      type: "slider",
      required: true,
      branch: "income",
      condition: {
        when_key: "primary_objective",
        when_values: ["INCOME", "BALANCE"],
      },
      scoring_dimension: "retirement_need",
      analytics_key: "lifetime_income_importance",
    },
    {
      id: "existing_guaranteed_income",
      number: 16,
      stage: "YOUR_PRIORITIES",
      label: "Existing guaranteed income",
      type: "cards",
      options: ["Pension", "Existing annuity", "Both", "Neither"],
      required: true,
      branch: "income",
      condition: {
        when_key: "primary_objective",
        when_values: ["INCOME"],
      },
      scoring_dimension: "retirement_need",
      analytics_key: "existing_guaranteed_income",
    },
    // Universal rejoined
    {
      id: "inflation_concern",
      number: 17,
      stage: "YOUR_PLAN",
      label: "Inflation concern",
      type: "slider",
      required: true,
      branch: "core",
      scoring_dimension: "retirement_need",
      analytics_key: "inflation_concern",
    },
    {
      id: "liquidity_importance",
      number: 18,
      stage: "YOUR_PLAN",
      label: "Emergency liquidity importance",
      type: "slider",
      required: true,
      branch: "core",
      scoring_dimension: "strategy_alignment",
      analytics_key: "liquidity_importance",
    },
    {
      id: "legacy_importance",
      number: 19,
      stage: "YOUR_PLAN",
      label: "Legacy importance",
      type: "slider",
      required: false,
      branch: "core",
      analytics_key: "legacy_importance",
    },
    {
      id: "healthcare_concern",
      number: 20,
      stage: "YOUR_PLAN",
      label: "Healthcare / LTC concern",
      type: "slider",
      required: false,
      branch: "core",
      scoring_dimension: "retirement_need",
      analytics_key: "healthcare_concern",
    },
    {
      id: "carrier_strength_importance",
      number: 21,
      stage: "YOUR_PLAN",
      label: "Carrier strength importance",
      type: "slider",
      required: false,
      branch: "core",
      analytics_key: "carrier_strength_importance",
    },
    {
      id: "advisor_team_importance",
      number: 22,
      stage: "YOUR_PLAN",
      label: "Advisor team importance",
      type: "slider",
      required: false,
      branch: "core",
      analytics_key: "advisor_team_importance",
    },
    {
      id: "current_advisor",
      number: 23,
      stage: "ALMOST_DONE",
      label: "Working with a financial professional?",
      type: "cards",
      options: [
        "Yes, actively",
        "Yes, but I'm considering alternatives",
        "Not currently",
      ],
      required: true,
      branch: "core",
      scoring_dimension: "intent_timing",
      analytics_key: "current_advisor",
    },
    {
      id: "advisor_improvement",
      number: 23,
      stage: "ALMOST_DONE",
      label: "What would you most like improved?",
      type: "cards",
      options: [
        "Growth",
        "Safety",
        "Income",
        "Fees",
        "Communication",
        "Tax efficiency",
        "Diversification",
        "Not sure",
      ],
      required: false,
      branch: "conditional",
      condition: {
        when_key: "current_advisor",
        when_values: [
          "Yes, actively",
          "Yes, but I'm considering alternatives",
        ],
      },
      analytics_key: "advisor_improvement",
    },
    {
      id: "decision_timeline",
      number: 24,
      stage: "ALMOST_DONE",
      label: "Decision timeline",
      type: "cards",
      options: [
        "Immediately",
        "Within 30 days",
        "1–3 months",
        "3–6 months",
        "6–12 months",
        "Just researching",
      ],
      required: true,
      branch: "core",
      scoring_dimension: "intent_timing",
      analytics_key: "decision_timeline",
    },
  ] satisfies AssessmentQuestionDef[],
};

export function getApplicableQuestions(answers: Record<string, string>) {
  return RETIREMENT_OPPORTUNITY_V1.questions.filter((q) => {
    if (!q.condition) return true;
    const value = answers[q.condition.when_key];
    return Boolean(value && q.condition.when_values.includes(value));
  });
}
